FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir watchdog
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8088

CMD ["watchmedo", "auto-restart", "--directory=/app", "--pattern=*.py", "--", "python", "-m", "bot.main"]
